Mobile
BrowserStackCE/browserstack-examples-nightwatchjs pull request #21
Opened 2022-04-08 07:32 UTC by Sankalan1987

2022-04-08 10:57 UTC, samirans89 commented
We need a handshake with TU team to commit on main as the Web automation TU courses use the same repo.

There also needs to be uniformity between the app, tests and other artefacts which are used in existing TU repos:

- browserstack-examples-appium-junit5
- browserstack-examples-appium-webdriverio
- browserstack-examples-appium-testng

2022-04-08 11:00 UTC, samirans89 requested changes

2022-04-08 11:00 UTC, samirans89 commented on src/app/pages/orders.js
> +			//	browser.assert.urlEquals(browser.url());
remove commented lines of code.

2022-04-08 11:00 UTC, samirans89 commented on README.md
remove .DS_Store

2022-04-08 11:00 UTC, samirans89 commented on README.md
> +curl -u "browserstack_username:browserstack_access_key" \
which app?

for main branch, the README doc approach has to be consistent with this one below:
https://github.com/browserstack/browserstack-examples-appium-testng#prerequisites

2022-04-11 06:14 UTC, Sankalan1987 commented on src/app/pages/orders.js
> +			//	browser.assert.urlEquals(browser.url());
Done.

2022-04-11 06:15 UTC, Sankalan1987 commented on README.md
Done.

2022-04-11 06:20 UTC, Sankalan1987 commented on README.md
> +curl -u "browserstack_username:browserstack_access_key" \
Done

2023-09-14 12:44 UTC, closed without merging